# Generated by Django 3.2.3 on 2023-11-22 18:37

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='цена товара', max_digits=10, verbose_name='Цена')),
                ('quantity', models.PositiveSmallIntegerField(help_text='количество', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='авторизованный', verbose_name='Авторизованный')),
                ('session_id', models.CharField(blank=True, help_text='id сессии', max_length=100, null=True, verbose_name='id сессии')),
                ('address', models.CharField(blank=True, help_text='адрес доставки заказа', max_length=500, null=True, verbose_name='Адрес')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='номер телефона', max_length=128, null=True, region=None, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, help_text='электронная почта', max_length=255, verbose_name='Почта')),
                ('comment', models.TextField(blank=True, help_text='текст комментария', null=True, verbose_name='Комментарии')),
                ('status', models.CharField(blank=True, default='создан', help_text='статус заказа', max_length=20, verbose_name='Статус заказа')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='дата создания', verbose_name='Дата создания')),
                ('user', models.ForeignKey(blank=True, help_text='id создателя заказа', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='дата создания', verbose_name='Дата создания')),
                ('comment', models.TextField(blank=True, help_text='текст комментария', null=True, verbose_name='Комментарии')),
                ('order', models.ForeignKey(help_text='id Заказа', on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='order.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Возврат',
                'verbose_name_plural': 'Возвраты',
            },
        ),
        migrations.CreateModel(
            name='CommodityRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='количество', verbose_name='Количество')),
                ('commodity', models.ForeignKey(help_text='id товара в заказе', on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='order.commodity', verbose_name='Возвращаемый товар')),
                ('refund', models.ForeignKey(help_text='id возврата заказа', on_delete=django.db.models.deletion.CASCADE, related_name='commodities', to='order.orderrefund', verbose_name='Возврат')),
            ],
            options={
                'verbose_name': 'Возвращаемый товар',
                'verbose_name_plural': 'Возвращаемые товары',
            },
        ),
        migrations.AddField(
            model_name='commodity',
            name='order',
            field=models.ForeignKey(help_text='id заказа', on_delete=django.db.models.deletion.CASCADE, related_name='commodities', to='order.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='product',
            field=models.ForeignKey(help_text='id товара в каталоге', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commodities', to='catalogue.product', verbose_name='Товар в заказе'),
        ),
        migrations.AddConstraint(
            model_name='commodityrefund',
            constraint=models.UniqueConstraint(fields=('commodity', 'refund'), name='unique_commodity_refund'),
        ),
        migrations.AddConstraint(
            model_name='commodity',
            constraint=models.UniqueConstraint(fields=('product', 'order'), name='unique_commodity_order'),
        ),
    ]
