# Generated by Django 3.2.3 on 2024-06-17 11:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='имя', max_length=255, verbose_name='имя')),
                ('last_name', models.CharField(help_text='фамилия', max_length=255, verbose_name='фамилия')),
                ('email', models.EmailField(help_text='электронная почта', max_length=255, verbose_name='почта')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='номер телефона', max_length=128, region=None, verbose_name='телефон')),
                ('order_id', models.IntegerField(help_text='id заказа', verbose_name='номер заказа')),
                ('order_date', models.DateTimeField(blank=True, help_text='дата заказа', verbose_name='дата заказа')),
                ('product_name', models.CharField(help_text='наименование товара', max_length=500, verbose_name='наименование продукта')),
                ('product_id', models.IntegerField(help_text='id товара', verbose_name='код товара')),
                ('quantity', models.PositiveSmallIntegerField(help_text='количество', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('reason', models.CharField(choices=[('erroneous order', 'Ошибочный заказ'), ('another reason', 'Другое (другая причина), пожалуйста укажите/приложите подробности'), ('error', 'Ошибка, пожалуйста укажите/приложите подробности'), ('wrong product', 'Получен не тот (ошибочный) товар'), ('damaged product', 'Получен/доставлен неисправным (сломан)')], max_length=17, verbose_name='причина возврата')),
                ('is_unpacked', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], help_text='укажите был ли распакован товар', verbose_name='товар распакован')),
                ('defect_description', models.TextField(blank=True, help_text='укажите выявленные дефекты товара', verbose_name='описание дефектов')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='дата создания', verbose_name='Дата создания')),
                ('order_refund', models.OneToOneField(blank=True, help_text='id возврата', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='order.orderrefund', verbose_name='возврат')),
            ],
            options={
                'verbose_name': 'Бланк возврата',
                'verbose_name_plural': 'Бланки возвратов',
            },
        ),
    ]
