# Generated by Django 3.2.3 on 2024-06-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderreturn_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreturn',
            name='order_date',
            field=models.DateField(blank=True, help_text='дата заказа', null=True, verbose_name='дата заказа'),
        ),
    ]
