version: '3.3'

volumes:
  static:
  media:

services:

  backend:
    build:
      context: ./maxboom_backend
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media

  nginx:
    build: ./nginx/
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - media:/app/media
      - static:/static/