version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13.10
    env_file: .env
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./maxboom_backend
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media

  nginx:
    build: ./nginx/
    env_file: .env
    restart: unless-stopped    
    ports:
      - 8000:80
    volumes:
      - media:/app/media
      - static:/static/