# Generated by Django 3.2.3 on 2023-09-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('-id',), 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
