# Generated by Django 3.2.3 on 2023-10-10 21:07

import catalogue.models
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=200, null=True, unique=True, verbose_name='Уникальный слаг')),
                ('is_prohibited', models.BooleanField(default=False, help_text='Бренд, которые не публикуются на сайте', verbose_name='Запрещенный для публикации производитель')),
                ('is_visible_on_main', models.BooleanField(default=False, help_text='Брэнд, которая отображаются на главной странице', verbose_name='Производитель на главной странице')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, max_length=1000, null=True, upload_to=catalogue.models.image_upload_path, verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=200, null=True, unique=True, verbose_name='Уникальный слаг')),
                ('wb_category_id', models.PositiveIntegerField(help_text='objectID на wildberries', unique=True, verbose_name='Id категории на wildberries')),
                ('is_visible_on_main', models.BooleanField(default=False, help_text='Категория, которая отображаются на главной странице', verbose_name='Категория видимая на главной странице')),
                ('is_prohibited', models.BooleanField(default=False, help_text='Категория, которая не публикуются на сайте', verbose_name='Запрещенная для публикации категория')),
                ('root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='catalogue.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=200, null=True, unique=True, verbose_name='Уникальный слаг')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Цена')),
                ('code', models.IntegerField(unique=True, verbose_name='Код товара')),
                ('vendor_code', models.CharField(max_length=100, unique=True, verbose_name='Артикул продавца')),
                ('imt_id', models.IntegerField(blank=True, null=True, verbose_name='id карточки на WB')),
                ('wb_urls', models.URLField(verbose_name='Ссылка на WB')),
                ('quantity', models.FloatField(default=999999, verbose_name='Количество')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удаленный товар')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalogue.brand', verbose_name='Производитель')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalogue.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(max_length=1000, upload_to=catalogue.models.image_upload_path, verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogue.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
            },
        ),
    ]
