# Generated by Django 3.2.3 on 2023-09-14 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='название')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='мета-название категории')),
                ('meta_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='мета-описание категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='цена')),
                ('brand', models.CharField(max_length=200, verbose_name='производитель')),
                ('code', models.IntegerField(unique=True, verbose_name='код товара')),
                ('wb_urls', models.URLField(verbose_name='ссылка на WB')),
                ('quantity', models.FloatField(default=999999, verbose_name='количество')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален ли товар')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-название товара')),
                ('meta_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание товара')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalogue.category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products_images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogue.product')),
            ],
            options={
                'verbose_name': 'Картинка товара',
                'verbose_name_plural': 'Картинки товаров',
            },
        ),
    ]
