# Generated by Django 3.2.3 on 2023-09-22 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='catalogue.category', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200, null=True, unique=True, verbose_name='Уникальный слаг'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200, null=True, unique=True, verbose_name='Уникальный слаг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200, null=True, unique=True, verbose_name='Уникальный слаг'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Эскиз'),
        ),
        migrations.DeleteModel(
            name='CategoryTree',
        ),
    ]
