# Generated by Django 3.2.3 on 2023-09-19 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Уникальный слаг')),
                ('is_prohibited', models.BooleanField(default=False, help_text='Бренды, которые не публикуются на сайте', verbose_name='Запрещенный для публикации производитель')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображения товаров'},
        ),
        migrations.AddField(
            model_name='category',
            name='is_prohibited',
            field=models.BooleanField(default=False, help_text='Категория, которая не публикуются на сайте', verbose_name='Запрещенная для публикации категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_visible_on_main',
            field=models.BooleanField(default=False, help_text='Категория, которая отображаются на главной странице', verbose_name='Категория видимая на главной странице'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalogue.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.BinaryField(max_length=200, unique=True, verbose_name='Уникальный слаг'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products_images', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogue.product', verbose_name='продукт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalogue.brand', verbose_name='бренд'),
        ),
    ]
