# Generated by Django 3.2.3 on 2024-04-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20240306_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='Вес товара, кг.'),
        ),
    ]
