# Generated by Django 3.2.3 on 2023-09-20 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20230920_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorytree',
            options={'verbose_name': 'Дерево категорий', 'verbose_name_plural': 'Деревья категорий'},
        ),
    ]
