# Generated by Django 3.2.3 on 2023-10-21 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Мета-название страницы для SEO', max_length=255, null=True, verbose_name='Мета-название страницы')),
                ('meta_description', models.CharField(blank=True, help_text='Мета-описание страницы для SEO', max_length=255, null=True, verbose_name='Мета-описание страницы')),
                ('title', models.CharField(help_text='Название категории', max_length=250, verbose_name='Название категории')),
                ('slug', models.SlugField(help_text='Слаг для категории', unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название тега', max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Мета-название страницы для SEO', max_length=255, null=True, verbose_name='Мета-название страницы')),
                ('meta_description', models.CharField(blank=True, help_text='Мета-описание страницы для SEO', max_length=255, null=True, verbose_name='Мета-описание страницы')),
                ('title', models.CharField(help_text='Заголовок поста', max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(help_text='Текст поста', verbose_name='Текст')),
                ('pub_date', models.DateField(auto_now_add=True, help_text='Дата создания поста', verbose_name='Дата публикации')),
                ('image', models.ImageField(blank=True, help_text='Изображние для поста', null=True, upload_to='blog/', verbose_name='Изображение')),
                ('views', models.PositiveIntegerField(default=0, help_text='Количество просмотров пользователями данного поста', verbose_name='Количество просмотров')),
                ('slug', models.SlugField(help_text='Слаг для поста', unique=True, verbose_name='Слаг')),
                ('author', models.ForeignKey(blank=True, help_text='Автор поста', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(blank=True, help_text='Категория, к которой относится пост', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(blank=True, help_text='Теги для поста.', related_name='posts', to='blog.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(help_text='Автор комментария', max_length=200, verbose_name='Имя')),
                ('text', models.TextField(help_text='Текст комментария', verbose_name='Комментарий')),
                ('pub_date', models.DateField(auto_now_add=True, help_text='Дата создания комментария', verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=False, help_text='Статус публикации комментария', verbose_name='Опубликован')),
                ('post', models.ForeignKey(help_text='Комментарий для данного поста', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-pub_date'],
            },
        ),
    ]
