# Generated by Django 3.2.3 on 2023-11-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20231102_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание страницы'),
        ),
        migrations.AlterField(
            model_name='news',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-название страницы'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Заголовок'),
        ),
    ]
