# Generated by Django 3.2.3 on 2023-11-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20231102_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение для новости', null=True, upload_to='news/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Мета-описание новости для SEO', max_length=255, null=True, verbose_name='Мета-описание страницы'),
        ),
        migrations.AlterField(
            model_name='news',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Мета-название новости для SEO', max_length=255, null=True, verbose_name='Мета-название страницы'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(auto_now_add=True, help_text='Дата создания новости', verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(help_text='Слаг для новости', unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(help_text='Тест для новости', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(help_text='Название новости', max_length=250, verbose_name='Заголовок'),
        ),
    ]
