# Generated by Django 3.2.3 on 2023-08-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(help_text='Введите заголовок страницы', max_length=255, verbose_name='Заголовок страницы')),
                ('text', models.TextField(help_text='Введите текст страницы', verbose_name='Текст страницы')),
            ],
            options={
                'verbose_name': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Agreements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(help_text='Введите заголовок страницы', max_length=255, verbose_name='Заголовок страницы')),
                ('text', models.TextField(help_text='Введите текст страницы', verbose_name='Текст страницы')),
            ],
            options={
                'verbose_name': 'Условия соглашения',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(help_text='Введите заголовок страницы', max_length=255, verbose_name='Заголовок страницы')),
                ('text', models.TextField(help_text='Введите текст страницы', verbose_name='Текст страницы')),
            ],
            options={
                'verbose_name': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='DeliveryInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(help_text='Введите заголовок страницы', max_length=255, verbose_name='Заголовок страницы')),
                ('text', models.TextField(help_text='Введите текст страницы', verbose_name='Текст страницы')),
            ],
            options={
                'verbose_name': 'Информация о доставке',
            },
        ),
        migrations.CreateModel(
            name='MainShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название магазина', max_length=255, verbose_name='Название магазина')),
                ('comment', models.CharField(max_length=255, verbose_name='Комментарий о магазине')),
                ('phone_number', models.CharField(help_text='Укажите номер телефона магазина', max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(help_text='Укажите адрес магазина', max_length=510, verbose_name='Адрес магазина')),
            ],
            options={
                'verbose_name': 'Основной магазин',
            },
        ),
        migrations.CreateModel(
            name='OurShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название магазина', max_length=255, verbose_name='Название магазина')),
                ('comment', models.CharField(max_length=255, verbose_name='Комментарий о магазине')),
                ('phone_number', models.CharField(help_text='Укажите номер телефона магазина', max_length=20, verbose_name='Номер телефона')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фотография')),
                ('is_main_shop', models.BooleanField(help_text='Укажите статус магазина как основного', verbose_name='Основной магазин')),
            ],
            options={
                'verbose_name': 'Наши магазины',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(help_text='Введите заголовок страницы', max_length=255, verbose_name='Заголовок страницы')),
                ('text', models.TextField(help_text='Введите текст страницы', verbose_name='Текст страницы')),
            ],
            options={
                'verbose_name': 'Политика безопасности',
            },
        ),
        migrations.CreateModel(
            name='Requisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisite_name', models.CharField(help_text='Укажите название реквизита', max_length=100, verbose_name='Название реквизита')),
                ('requisite_description', models.CharField(help_text='Укажите описание реквизита', max_length=255, verbose_name='Описание реквизита')),
            ],
            options={
                'verbose_name': 'Реквизиты',
            },
        ),
    ]
