# Generated by Django 3.2.3 on 2023-09-04 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='Contacts',
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterModelOptions(
            name='agreements',
            options={'verbose_name': 'Условия соглашения', 'verbose_name_plural': 'Условия соглашения'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='deliveryinformation',
            options={'verbose_name': 'Информация о доставке', 'verbose_name_plural': 'Информация о доставке'},
        ),
        migrations.AlterModelOptions(
            name='mainshop',
            options={'verbose_name': 'Основной магазин', 'verbose_name_plural': 'Основной магазин'},
        ),
        migrations.AlterModelOptions(
            name='ourshop',
            options={'verbose_name': 'Наши магазины', 'verbose_name_plural': 'Наши магазины'},
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name': 'Политика безопасности', 'verbose_name_plural': 'Политика безопасности'},
        ),
        migrations.AlterModelOptions(
            name='requisite',
            options={'verbose_name': 'Реквизиты', 'verbose_name_plural': 'Реквизиты'},
        ),
        migrations.AddField(
            model_name='mainshop',
            name='main_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_shop', to='core.contacts'),
        ),
        migrations.AddField(
            model_name='ourshop',
            name='main_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='our_shops', to='core.contacts'),
        ),
        migrations.AddField(
            model_name='requisite',
            name='main_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisites', to='core.contacts'),
        ),
        migrations.AlterField(
            model_name='mainshop',
            name='comment',
            field=models.CharField(help_text='Время работы и дополнительная информация', max_length=255, verbose_name='Комментарий о магазине'),
        ),
        migrations.AlterField(
            model_name='mainshop',
            name='email',
            field=models.EmailField(help_text='Введите электронную почту магазина', max_length=254, verbose_name='Почта магазина'),
        ),
        migrations.AlterField(
            model_name='ourshop',
            name='comment',
            field=models.CharField(help_text='Время работы и дополнительная информация', max_length=255, verbose_name='Комментарий о магазине'),
        ),
    ]
