# Generated by Django 3.2.3 on 2023-09-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230908_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание страницы'),
        ),
        migrations.AddField(
            model_name='about',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-название страницы'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание страницы'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-название страницы'),
        ),
        migrations.AddField(
            model_name='deliveryinformation',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание страницы'),
        ),
        migrations.AddField(
            model_name='deliveryinformation',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-название страницы'),
        ),
        migrations.AddField(
            model_name='privacy',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание страницы'),
        ),
        migrations.AddField(
            model_name='privacy',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-название страницы'),
        ),
        migrations.AddField(
            model_name='terms',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание страницы'),
        ),
        migrations.AddField(
            model_name='terms',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-название страницы'),
        ),
    ]
