# Generated by Django 3.2.3 on 2023-10-08 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopreviews',
            options={'ordering': ('-pub_date', 'id'), 'verbose_name': 'Отзыв о магазине', 'verbose_name_plural': 'Отзывы о магазине'},
        ),
    ]
